# Generated by Django 4.2.13 on 2024-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_dailylog_monthlylog_weeklylog_yearlylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearlylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
