# Generated by Django 4.2.13 on 2024-06-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_bulletjournalkey_alter_dailylog_key_and_more'),
    ]

    operations = [
    ]
